# Generated by Django 5.0.2 on 2024-03-05 09:06

import blog.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_image_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to=blog.models.image_sorter),
        ),
    ]
